### PR TITLE
Please add HexstreamSoft

### PR DESCRIPTION
**Pull request by Hexstream**
I humbly submit [HexstreamSoft](https://www.hexstreamsoft.com/), which is probably one of the most important Common Lisp companies despite not yet being formally registered. I so far made 3788$ CAD (including doublers) in [sponsorships](https://github.com/sponsors/Hexstream) this year, so I guess I'm finally a "real professional" by some measure. ;)

### CODE REVIEW

**Comment by azzamsa** [comment]
@vindarel is it OK?

**Comment by vindarel** [comment]
congrats for your sponsors!

So this is not a company per se. I think your presentation should mention it's a one-man umbrella, and that you live (nearly) on donations (which is an achievement). I'd drop the "#1" mention because we could add a similar mention to other companies, and it's a temporal fact that can change (and thus needs maintenance).

Not being a company you probably should stick to the maintainers list, no?

**Comment by Hexstream** [comment]
> congrats for your sponsors!

Thank you.

> So this is not a company per se. [...] Not being a company you probably should stick to the maintainers list, no?

Actually, **HexstreamSoft is effectively a 14 years old Common Lisp startup**.

I first did around 4.5 years of proprietary Common Lisp ("Hexstream Software", also unregistered), and then pivoted and open sourced everything as HexstreamSoft and then I've been doing Common Lisp Open Source for a decade. See [my LinkedIn profile](https://www.linkedin.com/in/hexstream) for details.

I just haven't yet formally registered HexstreamSoft as a company since that would have been a waste of time and money since I had (very nearly) no revenues, but that's finally starting to change so I'll probably register in the next few years.

(Have you personally ensured that every single company already on this list is formally registered? But I don't think that would be useful.)

> I think your presentation should mention it's a one-man umbrella

To what end? I don't think this would really provide any useful information, and "by Jean-Philippe Paradis (Hexstream)" is already prominent on the landing page. I'm not necessarily staunchly against it, but could you explain what value this would provide in the context of this list? That could help me write a better description.

> and that you live (nearly) on donations

Not quite the case yet, unfortunately, but I'm quite confident this will happen in the next few years at the most.

> I'd drop the "#1" mention because we could add a similar mention to other companies, and it's a temporal fact that can change (and thus needs maintenance).

I do think `#1 Common Lisp site according to Alexa as of October 2020.` is a pertinent fact, especially in the context of me being just one guy (who keeps getting censored for no reason, especially), and the "as of October 2020" part in fact makes it mostly "intemporal" (and thus not necessarily requiring maintenance) assuming that I won't drop below #1 in the 11 days remaining in the month. I also expect to further expand my lead by the end of the year (possibly after a temporary drop), and in the following years (I have quite a lot of awesome stuff coming up, and I'm not just talking about stuff in [my roadmap](https://roadmap.hexstreamsoft.com/)).

I guess I could censor that pertinent part for your comfort, if you require it. Do you?

**Comment by vindarel** [comment]
> I first did around 4.5 years of proprietary Common Lisp 

How did you make a living, did you have clients/users? (genuinely curious, glad if you can answer)

> To what end? I don't think this would really provide any useful information, and "by Jean-Philippe Paradis (Hexstream)" is already prominent on the landing page.

oh, indeed.

> I guess I could censor that pertinent part for your comfort, if you require it. Do you?

no strong feelings.

I think the most important is to state somehow that this is not properly speaking a company (you know, with clients, revenues, products etc).  You have more the profile of a "successful maintainer", IMO.

**Comment by Hexstream** [comment]
> How did you make a living, did you have clients/users? (genuinely curious, glad if you can answer)

I did not make a penny until 3 april 2020. (I had around 1000$ or less per year in "revenues" from the government and gifts from The Mom™.) I've been in Mom's Basement™ for 14 years.

There is some more background information in such places as [my LinkedIn profile](https://www.linkedin.com/in/hexstream), [my GitHub Sponsors profile](https://github.com/sponsors/Hexstream) and [my Patreon profile](https://www.patreon.com/Hexstream). I'm working on a pretty significant overhaul of my online presence, including all of these places and more.

> I think the most important is to state somehow that this is not properly speaking a company (you know, with clients, revenues, products etc).

***My clients* are [all Common Lispers interested in my work](https://twitter.com/HexstreamSoft/status/1317174473242574848), *my revenues* are [my sponsorships]() and *my products* are [everything at HexstreamSoft](https://www.hexstreamsoft.com/).**

**Comment by Hexstream** [comment]
So it's been *more than 2 weeks*, can we all leave this **humiliating extended discriminatory review period** behind us now?

By the way, [HexstreamSoft](https://www.hexstreamsoft.com/) has now been trending upwards for 60+ consecutive days, with 2 trivial exceptions.
[Daily Time On Site is 26 minutes.](https://www.alexa.com/siteinfo/hexstreamsoft.com)

Also, I published my professional profile, so [check out my CV!](https://cv.hexstream.expert/)

**Comment by vindarel** [comment]
(Note that I also have an open PR for ±2 weeks.)

**Comment by Hexstream** [comment]
What?! You mean #40? That's completely unrelated. I'll spare you a detailed analysis of the situation, but I'll simply point out that **11 of your own pull requests were merged on the *same day***, to wit: #12, #13, #14, #16, #17, #22, #24, #27, #30, #33, #38.

Of course my case is a bit higher-complexity, but I do always appreciate intellectual rigor.

That said, I guess I was technically mistaken about who I was waiting on.

@azzamsa, you asked vindarel about his opinion on this and we iterated a bit and he doesn't seem to be against merging this now.
Could you merge this now or do you have any objections?

**Comment by azzamsa** [comment]
I think "company" has a broad meaning. But since we already have TurtleWare, deftask, and other "one-man company. I will merge this PR.

**Comment by Hexstream** [comment]
Ah, thank you so much! ❤️

(The wait was grueling. 😅)

**Pull request merged**
