### PR TITLE
add SteelSeries

### PR DESCRIPTION
**Pull request by weinholt**
This commit adds SteelSeries, listing it under Denmark.

### CODE REVIEW

**Comment by vindarel** [comment]
Hello, thanks for the PR.

> their [open source Lisp written in Go](https://github.com/SteelSeries/golisp), which aims to be compatible with MIT/GNU Scheme.

I'm afraid this list focuses on Common Lisp :S We'll see what the maintainer says…

(you're more than welcome to post on /r/lisp)

**Comment by weinholt** [comment]
> I'm afraid this list focuses on Common Lisp :S We'll see what the maintainer says…

Well, that's fine by me, but there's this text above the list:

> This list intended only for company with Common Lisp and Scheme usage

**Comment by azzamsa** [comment]
All the current company that listed here is a Common Lisp company. But since I said

> This list intended only for company with Common Lisp and Scheme usage

and if golisp considered a "scheme" we should include it.

Or should we stick to Common Lisp only? What's your opinion @vindarel ?

**Comment by Hexstream** [comment]
> All the current company that listed here is a Common Lisp company.

Wonderful! Personally, I certainly hate to see Common Lisp being diluted into "lisp".

I can't be the only one who deeply cares about Common Lisp and deeply doesn't care about all other lisps...

**Comment by vindarel** [comment]
@weinholt good point^^

I am personally only interested in a Common Lisp list too. When I look for information or when I show this list for advertising, I expect to see CL examples.

@azzamsa: you could create a new list for Scheme?

**Comment by azzamsa** [comment]
> @azzamsa: you could create a new list for Scheme?

Currently, I am not interested. I never do any "serious" work with Scheme.

> I am personally only interested in a Common Lisp list too. When I look for information or when I show this list for advertising, I expect to see CL examples.

Since most/all the company here is CL company. I will rephrase to "This list intended only for a company with Common Lisp". Those who want to make the company list for the scheme can go with "awesome-scheme-companies".

I think we should stick to the repo name. Only rephrase the readme is necessary. @vindarel any comments?

**Comment by azzamsa** [comment]
After some check, I saw ~17 listed company that uses Scheme.

I took the inspiration from [Peter Christensen](http://pchristensen.com/blog/lisp-companies/) which was originally titled "Lisp Company" meaning to include Common Lisp and Scheme.

I think I will stick with "This list intended only for the company with **Common Lisp** and **Scheme** usage"

If the list grows more than expected. We should stop and make it a "curated/awesome list".

**Pull request merged**
