### PR TITLE
Add gensym corp

### PR DESCRIPTION
**Pull request by guojing0**
## Checklist

- [√] This company uses Common Lisp or Scheme in production

### CODE REVIEW

**Comment by Hexstream** [comment]
Nice!! I had no idea G2 was still being used in production...

**Comment by guojing0** [comment]
@Hexstream Maybe they mainly target enterprise and industry customers, so it's less known...

**Comment by vindarel** [comment]
Nice, thanks!

Are you better at google-fu than me, is there more information about G2 out there? There is this site and a mention on wikipedia.

**Comment by guojing0** [comment]
@vindarel Actually I am not sure. I follow a person (https://www.linkedin.com/in/binghelisp/, https://github.com/binghe) on Weibo (Chinese Twitter) who did work for Gensym and now is a PhD student at some school in Italy.

**Comment by Hexstream** [comment]
I think I have a PDF about G2 on my desktop. I'll check next time I boot it.

**Comment by Hexstream** [comment]
Sorry, it seems I must have deleted that G2 PDF when I realized I would never have time to read it...

**Pull request merged**
