### PR TITLE
add deftask

### PR DESCRIPTION
**Pull request by vindarel**
Hello, adding the new Deftask: https://deftask.com/ (currently the cli is open-sourced, he said on reddit to work on opening everything)

### CODE REVIEW

**Comment by azzamsa** [comment]
Oh, I know that he is a lisper from his tweet. Are you sure deftask built with CL ?

Btw, I think deftask based on India

**Comment by chaitanyagupta** [comment]
Hi @vindarel thanks for mentioning deftask here! One clarification: I plan to open source some of the deftask backend (and frontend) code, but not all of it. What I meant was that I planned to open source a lot more than just the deftask-cli.

@azzamsa deftask's backend is CL and Postgres. And yes, I am based in India :-)

**Comment by azzamsa** [comment]
@chaitanyagupta great app, good luck.

**Comment by azzamsa** [comment]
> @azzamsa this should appear before Tachyon which disappeared, right ?

https://github.com/azzamsa/awesome-lisp-companies#india

Yes

**Comment by vindarel** [comment]
and 

> Deftask use

-> uses

**Comment by chaitanyagupta** [comment]
Hi @azzamsa thanks for adding deftask.

> Deftask uses Common Lisp in their applications

A more accurate description would be that the deftask backend and the command-line app are written in CL.

**Comment by azzamsa** [comment]
> A more accurate description would be that the deftask backend and the command-line app are written in CL.

Or if you want to add more, we love your PR :), so the description very specific from you.

**Pull request merged**
