### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pdelfino**
Add information about Atlas Engineer building the Nyxt browser.

## Checklist

- [x] This company uses Common Lisp in production.

Source code showing the use of [Common Lisp](https://github.com/atlas-engineer/nyxt).

### CODE REVIEW

**Comment by vindarel** [comment]
Hello, I have mixed feelings, because:

- behind the atlas.engineer website or "company" is one man
- they live off a european grant, they don't make income differently
  - it's cool but is that a company we can be proud about in this awesome list, that says "look, Lisp is successful for business!" when they don't really run a business.
- " data analysis, crawling," they don't do any of this, AFAIK.
- from their About page: "engineering firm based in Chicago, Paris, and Berlin": it's one guy living in Berlin coming from Chicago and the other main Nyxt developer living in Paris.
- Product catalog -> Product page -> one "product", Nyxt. Mixed feelings.

**Comment by Hexstream** [comment]
Your reaction is bizarre and unexpected.

Atlas Engineer is definitely more company-like than HexstreamSoft in a few ways, and HexstreamSoft did (finally) make the cut, although I inexplicably had to [fight for it](https://github.com/azzamsa/awesome-lisp-companies/pull/39).

For one thing, Atlas Engineer has actually employed a few people, including *yourself* for almost a year, right?

I haven't tried Nyxt, but it seems at least pretty close to commercial product quality, and they completely obliterate me in terms of GitHub Stars at 4.1k VS I think less than 0.1k?

Atlas Engineer got an actual government grant? I can only dream of receiving one.

So yeah, this case is pretty open-and-shut for me, and I am amazed that it is not for you as well, although it is not the first time I am surprised and disappointed by your analyses.

**Comment by vindarel** [comment]
> For one thing, Atlas Engineer has actually employed a few people, including yourself for almost a year, right?

I was not employed by Atlas when I committed to Nyxt (I actually was employed for a closed-source web project for one month, prior Nyxt). I joined the team because they contacted me, because the project is awesome and because I was in-between a real job and my independent activity. I signed a thing saying I was not paid, but we counted the hours, and if/when the company were successful I would be compensated with the due $. I received twice a little income at the end, when the first grant was approved, but it was time for me to stop.

> Atlas Engineer is definitely more company-like than HexstreamSoft in a few ways, and HexstreamSoft did make the cut in the end

that's right, and people looking at this list see HexstreamSoft, see it isn't a real company as they expect it, so they doubt of the awesomeness of the list.

> pretty close to commercial product quality

maybe, maybe not, it is not a commercial product anyways.

Sorry to disappoint you ;) This was my 2c, it explains why I'm not merging straight-in. I think Nyxt is a great showcase of a Lisp project, but Atlas isn't a good showcase for a (Lisp) company. Open to more feedback.

**Comment by Hexstream** [comment]
> that's right, and people looking at this list see HexstreamSoft, see it isn't a real company as they expect it, so they doubt of the awesomeness of the list.

What people? Shitty people? Why would anyone care about the opinions of shitty people? Do you? Maybe that's the core problem with some of your analyses? Just a thought...

The primary effect of not registering HexstreamSoft as a "real" company has been saving thousands of dollars I never even had over 15 years. Also note that this is effectively poor-shaming. And efficiency-shaming. HexstreamSoft has been delivering tremendous value at extremely little cost. I could say much more, but maybe it would start to sound like bit of an ad, so I guess I'll stop here.

**Comment by vindarel** [comment]
random comments on Hacker News for example. Call it blind customer study :p But no pb, this issue isn't about HexstreamSoft.

**Comment by Hexstream** [comment]
Ah, so random shitty people on Hacker News, then? Okay...

**Comment by vindarel** [comment]
@pdelfino  Thanks for the PR anyways :)

**Comment by Hexstream** [comment]
So I made a simple comments search for "HexstreamSoft" on HN, and apparently [this single random comment is your entire "blind customer study"](https://news.ycombinator.com/item?id=28831487), and has apparently completely swayed you.

I don't feel I need to explain how profoundly ridiculous this is, and I'm not sure I can regard you as a person of sane judgement after this.

Kind regards.

**Pull request closed without merging**
